name: Review Environment Cleanup

on:
  pull_request:
    branches:
      - main
    types:
      - closed

# Generate a GitHub token that can be exchanged with Google Cloud - see
# https://github.com/google-github-actions/auth/tree/v0.6.0#setting-up-workload-identity-federation
permissions:
  contents: read
  id-token: write
  deployments: write # Allows removing deployments on GitHub

jobs:
  teardown_deployment:
    name: Teardown deployment
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLOUD_SQL_INSTANCE: postgres-dev-a

    steps:
      # actions/checkout MUST come before auth
      - name: Checkout the code
        uses: actions/checkout@v3.1.0

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1.0.0
        with:
          service_account: github-actions-runner@rails-google-cloud-quickstart.iam.gserviceaccount.com
          workload_identity_provider: projects/000000000000/locations/global/workloadIdentityPools/devops/providers/github

      - name: Set up gcloud Cloud SDK environment
        uses: google-github-actions/setup-gcloud@v1.0.0

      - name: Remove the deployed service from Cloud Run
        run: |-
          gcloud run services delete \
            rails-google-cloud-quickstart-pr${{ github.event.pull_request.number }} \
            --quiet \
            --platform=managed \
            --region=us-central1

      - name: Drop the review database
        run: |-
          gcloud sql databases delete \
            rails_google_cloud_quickstart_pr${{ github.event.pull_request.number }} \
            --quiet \
            --instance=pg-fourteen-a

      - name: Deactivate & remove the deployment from Github
        uses: bobheadxi/deployments@v1.3.0
        if: always()
        with:
          step: delete-env
          token: ${{ github.token }}
          env: ${{ github.head_ref }}
